name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧩 Clonar repositório
        uses: actions/checkout@v3

      - name: 🎨 Gerar gráfico estilo Pacman
        uses: yoshi389111/github-profile-pacman@main
        with:
          github_user_name: OtavioAugustodaRoza
          svg_out_path: dist/
          color_body: '#000000'
          color_eye: '#FFD700'
          color_cake: '#00FFFF'

      - name: 📤 Fazer upload do resultado
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
